default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DB_HOST') { '127.0.0.1' } %>

development:
  <<: *default
  database: inss_discount_development
  username: <%= ENV.fetch('DATABASE_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'password' } %>
test:
  <<: *default
  database: inss_discount_test
  username: <%= ENV.fetch('DATABASE_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'password' } %>

production:
  <<: *default
  database: inss_discount_production
  username: inss_discount
  password: <%= ENV["INSS_DISCOUNT_DATABASE_PASSWORD"] %>
